services:
#  app:
#    build: .
#    ports:
#      - "8000:8000"
#    depends_on:
#      - elasticsearch
#      - db
#      - minio
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE}
#      - GIGACHAT_TOKEN=${GIGACHAT_TOKEN}
#      - GIGACHAT_MODEL=${GIGACHAT_MODEL}
#      - MINIO_URL=${MINIO_URL}
#      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
#      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
#      - MINIO_BUCKET=${MINIO_BUCKET}
#      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
#      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  elasticsearch:
    image: elasticsearch:8.17.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: [ "server", "/data", "--console-address", ":9001" ]

volumes:
  db_data:
  es_data:
  minio_data:
